"""
curator/git_publisher.py

Handles:
1. Initializing or verifying a local git repo in the project root
2. Creating a private GitHub repo if it doesn't exist (via PyGithub)
3. Committing the generated README.md
4. Pushing to the remote private repo using the GitHub PAT

Requires GITHUB_TOKEN, GITHUB_USERNAME, and GITHUB_REPO_NAME in .env.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

from curator.config import GITHUB_REPO_NAME, GITHUB_TOKEN, GITHUB_USERNAME, README_PATH

_ROOT = Path(__file__).parent.parent


def _run(cmd: list[str], check: bool = True, capture: bool = False) -> subprocess.CompletedProcess:
    return subprocess.run(
        cmd,
        cwd=_ROOT,
        check=check,
        capture_output=capture,
        text=True,
    )


def _git_init() -> None:
    """Initialize git repo if not already initialized."""
    git_dir = _ROOT / ".git"
    if not git_dir.exists():
        _run(["git", "init", "-b", "main"])
        print("  ✅ Initialized git repository.")
    else:
        print("  ✅ Git repository already initialized.")


def _ensure_remote(remote_url: str) -> None:
    """Add or update the 'origin' remote."""
    result = _run(["git", "remote", "-v"], capture=True, check=False)
    if "origin" in result.stdout:
        _run(["git", "remote", "set-url", "origin", remote_url])
        print(f"  ✅ Updated remote origin → {remote_url}")
    else:
        _run(["git", "remote", "add", "origin", remote_url])
        print(f"  ✅ Added remote origin → {remote_url}")


def _create_github_repo_if_missing() -> str:
    """
    Uses PyGithub to create the private repo if it doesn't exist.
    Returns the HTTPS clone URL with embedded token for push auth.
    """
    if not GITHUB_TOKEN:
        raise EnvironmentError(
            "GITHUB_TOKEN is not set. Add it to your .env file.\n"
            "Create a PAT at: https://github.com/settings/tokens (scope: repo)"
        )
    if not GITHUB_USERNAME:
        raise EnvironmentError("GITHUB_USERNAME is not set in .env")

    from github import Github, GithubException

    gh = Github(GITHUB_TOKEN)
    user = gh.get_user()

    try:
        repo = user.get_repo(GITHUB_REPO_NAME)
        print(f"  ✅ GitHub repo already exists: {repo.html_url}")
    except GithubException:
        print(f"  📦 Creating private GitHub repo: {GITHUB_REPO_NAME} ...")
        repo = user.create_repo(
            GITHUB_REPO_NAME,
            private=True,
            description="🤖 AI-curated Android root & kernel knowledge base — auto-generated by knowledge-curator",
            has_issues=True,
            has_wiki=False,
            auto_init=False,
        )
        print(f"  ✅ Created: {repo.html_url}")

    # Embed token in URL for push authentication (token never committed)
    auth_url = f"https://{GITHUB_USERNAME}:{GITHUB_TOKEN}@github.com/{GITHUB_USERNAME}/{GITHUB_REPO_NAME}.git"
    return auth_url


def _configure_git_identity() -> None:
    """Set git user config if not already set (needed for bare environments)."""
    result = _run(["git", "config", "user.email"], capture=True, check=False)
    if not result.stdout.strip():
        _run(["git", "config", "user.email", "knowledge-curator@local"])
        _run(["git", "config", "user.name", "Knowledge Curator Bot"])


def publish(commit_message: str = "chore: update curated knowledge base") -> None:
    """
    Full publish pipeline:
    1. Init git
    2. Create GitHub repo if missing
    3. Commit README.md
    4. Push to main branch

    Raises:
        EnvironmentError: If GitHub credentials are missing
        subprocess.CalledProcessError: If any git command fails
    """
    print("\n📤 Publishing to GitHub...")

    _git_init()
    _configure_git_identity()
    auth_url = _create_github_repo_if_missing()
    _ensure_remote(auth_url)

    # Stage README.md (and .gitignore if present)
    files_to_add = [str(README_PATH.relative_to(_ROOT))]
    gitignore = _ROOT / ".gitignore"
    if gitignore.exists():
        files_to_add.append(".gitignore")

    _run(["git", "add"] + files_to_add)

    # Check if there's anything to commit
    result = _run(["git", "status", "--porcelain"], capture=True, check=False)
    if not result.stdout.strip():
        print("  ℹ️  Nothing to commit — README.md is already up to date.")
        return

    _run(["git", "commit", "-m", commit_message])
    print(f"  ✅ Committed: '{commit_message}'")

    # Push (force-safe: uses --set-upstream on first push)
    push_result = _run(
        ["git", "push", "--set-upstream", "origin", "main"],
        check=False,
        capture=True,
    )
    if push_result.returncode != 0:
        # If branch already exists upstream, regular push
        _run(["git", "push", "origin", "main"])

    print(f"  🚀 Pushed to: https://github.com/{GITHUB_USERNAME}/{GITHUB_REPO_NAME}")
